[package]
name    = "quad"
version = "0.0.0"
authors = [ "You" ]
resolver="2"

[dependencies]
bevy = "0.8.0"
bevy_rapier3d = { version = "0.16.0", features = [ "simd-stable", "dim3",  "debug-render"], default-features=false }
